title: Dandy Cat Labs

author: SlateBrick

description: >
  Finding the joy in making, 
  following the path less traveled
  Bringing the imagined into reality

remote_theme: jekyll/architect

plugins:
  - jekyll-remote-theme
