title: Dandy Cat Labs

author: 
  name: SlateBrick
  email: test@test.com
  
description: Everything I make

remote-theme: jekyll/minima

#header_page:
#  - about.md

minima:
  skin: auto
