title: Dandy Cat Labs

author: SlateBrick
  
description: Everything I make

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

minima:
  skin: dark
