title: Dandy Cat Labs

author: SlateBrick

description: >
  Finding the joy in making, 
  following the path less traveled
  Bringing the imagined into reality

remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme
