title: Dandy Cat Labs

author: SlateBrick

description: >
  Finding the joy in making, 
  following the path less traveled
  Bringing the imagined into reality

remote_theme: jekyll/minima

plugins:
  - jekyll-feed  
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - about.md


minima:
  skin: dark

