title: Dandy Cat Labs

author: 
  name: SlateBrick
  email: test@domain.com
  
description: >
  Finding the joy in making, 
  following the path less traveled
  Bringing the imagined into reality

remote_theme: jekyll/architect

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - about.md
