title: Dandy Cat Labs

author: 
  name: SlateBrick
  email: test@domain.com
  
description: >
  Finding the joy in making, 
  following the path less traveled
  Bringing the imagined into reality

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: instagram,      user_url: "https://www.instagram.com/dandycatlabs/" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCVWvkXXXVP52vxdrMjT3YKw" }
    - { platform: rss,            user_url: "https://slatebrick.github.io/Dandy-Cat-Labs/feed.xml" }
    - { platform: printables,     user_url: "https://www.printables.com/@DandyCatLabs_222320" }
